# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the comma`nds below to build your repository.
          - export SYSTEMCTL_NAME=kestrel-mikrotik
          - export PROJECT_NAME=MikroTik.WebApi
          - export PROJECT_PATH=/var/www/imrobot.info/tik
          - export REPO_GIT=https://mehaX@bitbucket.org/mehaxsvr/mikrotik.git
          - export REPO_GIT_NAME=mikrotik
          - cd /usr/src/deployments
          - git clone $REPO_GIT $REPO_GIT_NAME
          - cd $REPO_GIT_NAME
          - dotnet restore
          - dotnet build $PROJECT_NAME
          - dotnet publish $PROJECT_NAME -c Release
