# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        script: # Modify the comma`nds below to build your repository.
          - ssh root@imrobot.info ~/mikrotik-deploy.sh > output.log
